### ISSUE TITLE
only one single CWT allowed on RS

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-oscore-profile#20]
@jimsch Please review the update CWT example with the most recent profile text
on having only a single CWT on the RS.  I don't know that this needs an
update but it probably does.

**Comment by fpalombini** [comment]
Apologies for not being up to date here, but I was looking for text about the RS only having a single token, I found this text [in the framework](https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-24#section-5.8.1):

>    This specification RECOMMENDS that an RS stores only one token per
>    proof-of-possession key, meaning that an additional token linked to
>    the same key will overwrite any existing token at the RS.

Which goes well with what is today in the profile:

> When receiving an updated access token with updated authorization information from the client (see section Section 3.1), it is RECOMMENDED that the RS overwrites the previous token, that is only the latest authorization information in the token received by the RS is valid. This simplifies for the RS to keep track of authorization information for a given client.

Where is the text about one single CWT allowed on RS? and is the above text then wrong?

**Comment by LudwigSeitz** [comment]
Both texts reflect my intention and what I understood the WG agreed to. An RS might need to store different access tokens for different clients, but not several access tokens for the same client, since that is a can of worms for when you have an ongoing interaction (e.g. a DTLS session) between a client and RS and one of the tokens expires (thus reducing the set of access rights).

**Comment by fpalombini** [comment]
Thanks @LudwigSeitz , that is what I thought and what is also already stated in the profile.

I thought that what @jimsch was saying is that now that is not "RECOMMENDED" anymore but "REQUIRED" in the framework, which would have requested an update of the profile. So if @jimsch is ok with this, I'll close this issue.

**Comment by jimsch** [comment]
Identification that two tokens refer to the same <key identifier, key> pair is simple even if one has disposed of the CWT.  This means that keeping the same DTLS channel open and upgrading the permissions is simple.  This is far more difficult with OSCORE.  Posting a new token will generate a new key pair, even if the same ids and secret are used because of the nonce changes and more information needs to be kept to figure out if two CWTs refer to the same client.  Not sure what could be updated but I am still trying to figure out how to do this.

**Comment by fpalombini** [comment]
I think with the additional clarifications about deriving a security context and replacing the old one,  I don't really see what else we want to add. The following sentence is the one implicitly stating the association between C (and its authorization information) and derived security context at the RS.
> The RS then uses this Security Context to verify requests and send responses to C using OSCORE.

**Comment by jimsch** [comment]
I think you are missing my problem.  Consider the following:
1.  Client posts token T1 to RS and creates a security context A.
2.  Client sets up an observe on resource /foo/bar using the security context A.
time passes
3.  Client needs to update the token and gets a new token from the AS
4.  Client posts the new token (T2) to the RS and creates a security context B.
If the RS can recognize that T1 and T2 are for the same client, it is supposed to replace T1 with T2 and update any security evaluations under the new token include the observation from 2.
If the RS cannot recognize that T2 and T1 are for the same client, then it will have both tokens within it's set of tokens.
For DTLS the matching is relatively easy as T2 would normally be posted over the DTLS channel established with T1.  The key should be the same but other than that no issues arise.  If there is not DTLS channel open then you cannot have any active observes in process.  (If you do then life gets really wierd.
For OSCORE, I guess you could require that the token T2 be posted using token T1 so that the first step occurs, but otherwise the matching is difficult and there can be open security contexts unlike DTLS as the OSCORE channel is never "closed".

**Comment by fpalombini** [comment]
Thanks for your patience explaining Jim :) I think I got it. I drafted a long email and sent it to the mailing list, as I believe this requires more discussion/wg agreement https://mailarchive.ietf.org/arch/msg/ace/dLkW-MYHXfZqmtY7AP7ZBDJpxOw/

**Comment by fpalombini** [comment]
Should be fixed in 351928560a.
