### ISSUE TITLE
conflict with existing CWT

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-oscore-profile#21]
@jimsch If the AS creates a new, from scratch, CWT with the same clientId in the
case of a change in permissions, what happens with regards to the RS
matching to an existing context as oppose to treating it as a conflict.
This is going to be potentially even more of a problem in the case that the
RS changed the client ID and did not keep the full CWT around.

**Comment by fpalombini** [comment]
Sorry @jimsch I don't understand the scenario, could you expand? This is what I get from your comment:

* C and RS have an existing security context in place with ClientId = CID
* C requests a new token with different permissions but same security context (so including CID not a new full sec ctx)
* C receives that and posts to RS as usual (So creating new nonces etc) -> different security context is derived in the end
* C and RS use the updated (new) security context with same ClientID CID

What is the conflict you are talking about?

**Comment by jimsch** [comment]
In step #3 above - 
1. RS gets a new CWT posted to it
2. Does this match a CWT that I currently have?  No
3. Does this match a "kid" that I currently have?  If it does then I can kill the old context associated with the CWT and replace it with a new context association if they match to some degree - specifically the same secret, etc.  If they do not match then generate a new client id and send back.
Implications:
If new secrets are created in order to make the session last longer, then the old context is not deleted and two contexts now exist on the RS.  
If the RS assigned a new client ID during the original context creation process, then the secrets do not match and a two contexts will now exist on the RS for the client (three if you include the client that had the original collision).
If you discard the CWT and OSCORE context derivation information and just keep the scope and derived context you can never match back to an original CWT when a new CWT comes in.  The nonces will guarantee that the derived context never matches.

**Comment by fpalombini** [comment]
> If new secrets are created in order to make the session last longer, then the old context is not deleted and two contexts now exist on the RS.

Right, the text about delete the old context if the new one is derived is missing, I should add that.

> If the RS assigned a new client ID during the original context creation process, then the secrets do not match and a two contexts will now exist on the RS for the client 

Yes, that might be ok, if the client is accessing a different resource that has nothing to do with the first one, for which it wants different keying material... I would leave it to the application to decide if this is ok, but I'd rather not remove this feature (it's a feature, not a bug!)

> (three if you include the client that had the original collision).

Yes, three context but none is colliding (2 for one client, 1 for another client) but none is colliding.

> If you discard the CWT and OSCORE context derivation information and just keep the scope and derived context you can never match back to an original CWT when a new CWT comes in. The nonces will guarantee that the derived context never matches.

Yes, that's right, do you see this as a problem?

**Comment by jimsch** [comment]
Yes I see this as a problem.  Consider the following scenario.

I post CWT #1 to the server and derive context #1 
I setup an observe on a resource using context #1 
I ask for expanded capabilities from the AS and pass up the CWT #1 information and get back CWT #2 
I post CWT #2 to the server and derive context #2 

Do I go through everything and replace all references to context #1 with context #2 - remembering that until I get a first round trip with it I don't know that we have agreed on all of the nonces for derivation?  Not to mention that any messages in flight are going to end up with a no matching context.

Does the server just replace the capabilities of the client in context #1 with those from CWT #2 and the context #2 is just dropped on the ground and forgotten?

**Comment by fpalombini** [comment]
> Does the server just replace the capabilities of the client in context #1 with those from CWT #2 and the context #2 is just dropped on the ground and forgotten?

Going back to this: yes, that is what I would expect an implementation to do, if observe needs to be kept alive. But I don't see many problems with the RS cancelling the observation (CoAP observe is specified so that "keep alive" is something that the client is supposed to be doing anyway). Same for messages in flight that are lost, that is to be accounted for with CoAP.

I will add a paragraph with these considerations in section 6 "Discarding the Security Context". Let me know if that's good enough.
